### ISSUE TITLE
[QUESTION]

### ISSUE THREAD

**Issue by johntaxmi** [abcboy101/discordtrivia#1]
How to break an question into two lines.
like
what is my favourite color?
1.Red
2.Blue
3.Black

and the answer be black.
i tried doing the \n that works for discord.js but that is a txt file and it just continues in the same line.

Also an other question, how can i add multiply answers into one question?

**Comment by abcboy101** [comment]
> How to break an question into two lines.

This isn't supported yet, may add this in the future.

> Also an other question, how can i add multiply answers into one question?

You can add multiple answers by using multiple `*`, for example: `Question*A*B` would accept either A or B as an answer.

**Comment by abcboy101** [comment]
> This isn't supported yet, may add this in the future.

And fixed in 7639f56.
