### ISSUE TITLE
how does download work

### ISSUE THREAD

**Issue by Sylvamy** [abcboy101/discordtrivia#3]
How does the Download option work? do i set it to download a .txt file thats setup the same as questions.txt? i dont understand

**Comment by abcboy101** [comment]
Whenever the trivia game starts, any URL that can be downloaded as a .txt file will overwrite the file at `filepath` in `settings.txt`. This is useful if you have the question list on a server/a repo/a Google Doc, etc. and you want to make sure it's up-to-date whenever a game starts.

**Comment by Sylvamy** [comment]
i attempt to download it from my webserver http://benrulez.com/download/trivia/questions/AvatarTheLastAirbender.txt
but it says download failed everytime :(

**Comment by abcboy101** [comment]
I'm hitting Cloudflare DDOS protection on that link, which is probably preventing the bot from accessing it. You might want to disable Cloudflare DDOS protection on that folder/from your bot's IP/etc. so that the bot can access it programmatically.

**Comment by Sylvamy** [comment]
🤦 silly me
